### ISSUE TITLE
MDN storage investigation: S3 vs EFS

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#183]
[Parent issue](https://github.com/mozmar/infra/issues/147)

Determine the tradeoffs between S3 and EFS for storing and serving files.

More info [here](https://docs.google.com/document/d/1_JtwNQv2zyrVkZ3mLuu3-zEVbrwaVH8ErdDTe4GUy9U/edit#heading=h.88l66nuhk518)

At a high level, we need storage for the following object types:
(highlights taken from the doc above)

- **Bulk uploads**
  - large files, uploaded by staff
  - some need `latest` URL
  - no prod/staging distinction
- **Static assets**
  - js, css, images. 
  - generated by Kuma, 
  - Uploaded via prod push
  - trusted and executable by CSP
  - perf critical (CloudFront)
  - maintain prod/staging/other environments
- **User uploads**
  - MIME types configured in Django Admin (images, fonts, HTML)
  - tracked in MDN DB
  - performance is important, as they are embedded into pages
  - JS allows, served from different domain
  - maintain prod/staging/local environments
  - local attachments work by redirecting to prod file
- **Legacy files**
  - small to large files (vode, no JS/CSS)
  - not updated in 5-10 years
  - no prod/staging distinction
- **Legacy samples**
  - never update == read only
  - requires JS execution, inline CSS etc
  - not considered important for site performance
  - no prod/staging distinction
  - This has been [a target](https://bugzilla.mozilla.org/show_bug.cgi?id=1076893) to move since 2014.

**Comment by metadave** [comment]
@jgmize @jwhitlock The Toronto conversation is a bit foggy to me now, does Kuma need to work to incorporate S3, while EFS could be plugged in without changes?

**Comment by jgmize** [comment]
@metadave yes, we should be able to set up a PVC backed by EFS and use it without changes to the kuma codebase, and it may have some performance advantages as well. I think we should test that first and then decide if the s3 alternative is worth the development effort.

**Comment by jgmize** [comment]
For more context, at the time we originally planned for s3, neither EFS nor k8s PVCs were available.

**Comment by metadave** [comment]
I experimented a bit with EFS, and it worked! 
Here's a crude example of the K8s objects I deployed:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mdn-uploads-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/"
    server: <populate from EFS console>
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mdn-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: mdn-uploads-pv
---
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: mdn-uploads-storage
      persistentVolumeClaim:
       claimName: mdn-uploads-pvc
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/mdn"
          name: mdn-uploads-pvc
  volumes:
    - name: mdn-uploads-pvc
      persistentVolumeClaim:
        claimName: mdn-uploads-pvc
```

After exec'ing bash on the `task-pv-pod`, I was able to write to `/mdn/foo`. I launched a new EC2 instance and was able to see the file.

**Comment by metadave** [comment]
useful notes on EFS [here](https://github.com/open-guides/og-aws#efs-basics)

**Comment by metadave** [comment]
Change the pod to a Deployment w/ 3 replicas, and was easily able to write and see data shared between pods. 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pvtest
  namespace: metadave
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pvtest
    spec:
      volumes:
        - name: mdn-uploads-storage
          persistentVolumeClaim:
          claimName: mdn-uploads-pvc
      containers:
        - name: task-pv-container
          image: nginx
          volumeMounts:
            - mountPath: "/mdn"
              name: mdn-uploads-pvc
      volumes:
        - name: mdn-uploads-pvc
          persistentVolumeClaim:
            claimName: mdn-uploads-pvc
```
